services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: hera
      POSTGRES_PASSWORD: hera300619
      POSTGRES_DB: hera
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'

volumes:
  postgres_data: